/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.border.TitledBorder;
import mainscreen.PlayerScreen;
import model.PlayerInfo;

/**
 *
 * @author thuy
 */
public class PlayerInfoPane extends javax.swing.JPanel {

    /**
     * Creates new form PlayerInfoPane
     */
    PlayerInfo player;

    public PlayerInfoPane(PlayerInfo p) {
        initComponents();

        setBackground(new Color(0, 0, 0, 64));

        player = p;

        TitledBorder titleBorder = new TitledBorder(this.getBorder(), "RANK " + player.getRank());
        titleBorder.setTitleFont(new Font("Ink Free", Font.BOLD, 30));
        titleBorder.setTitleColor(Color.white);
        titleBorder.setTitleJustification(TitledBorder.CENTER);
        titleBorder.setTitlePosition(TitledBorder.TOP);
        setBorder(titleBorder);

        lblName.setText(player.getName());
        lblScore.setText(player.getScore() + "");
        avaView.add(new ImagePane(new ImageIcon(player.getAva()).getImage()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avaView = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();

        setBackground(new Color(0, 0, 0, 64));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        avaView.setOpaque(false);
        avaView.setPreferredSize(new java.awt.Dimension(200, 200));
        avaView.setLayout(new java.awt.BorderLayout());
        add(avaView, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 10));

        lblName.setFont(new java.awt.Font("Ink Free", 1, 30)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        jPanel2.add(lblName);

        lblScore.setFont(new java.awt.Font("Ink Free", 1, 30)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setText("Score");
        jPanel2.add(lblScore);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel avaView;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables

}
