/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import mainscreen.PlayerScreen;
import model.PlayerInfo;
import model.Room;

/**
 *
 * @author thuy
 */
public class RoomInfoPane extends javax.swing.JPanel implements MouseListener {

    /**
     * Creates new form RoomInfoPane
     */
    Room room;
    PlayerInfo player1;
    PlayerInfo player2;
    PlayerScreen mainscreen;
    int curPID;

    public RoomInfoPane(Room r, PlayerInfo p1, PlayerInfo p2, PlayerScreen fr) {
        initComponents();

        mainscreen = fr;

        setBackground(new Color(0, 0, 0, 64));

        room = r;
        player1 = p1;
        player2 = p2;

        TitledBorder titleBorder = new TitledBorder(this.getBorder(), "ROOM " + r.getRoomID());
        titleBorder.setTitleFont(new Font("Ink Free", Font.BOLD, 30));
        titleBorder.setTitleColor(Color.white);
        titleBorder.setTitleJustification(TitledBorder.CENTER);
        titleBorder.setTitlePosition(TitledBorder.TOP);
        setBorder(titleBorder);

        if (player1 == null) {
            ImagePane btnFight = new ImagePane(new ImageIcon("images/fight.png").getImage());
            ava1View.setLayout(new GridBagLayout());
            ava1View.add(btnFight);
            curPID = 1;
            btnFight.addMouseListener(this);
            lblNameP1.setText("");
        } else {
            ava1View.add(new ImagePane(new ImageIcon(player1.getAva()).getImage()));
            lblNameP1.setText(player1.getName());
        }

        if (player2 == null) {
            ImagePane btnFight = new ImagePane(new ImageIcon("images/fight.png").getImage());
            ava2View.setLayout(new GridBagLayout());
            ava2View.add(btnFight);
            curPID = 2;
            btnFight.addMouseListener(this);
            lblNameP2.setText("");
        } else {
            ava2View.add(new ImagePane(new ImageIcon(player2.getAva()).getImage()));
            lblNameP2.setText(player2.getName());
        }

        vsView.add(new ImagePane(new ImageIcon("images/vs.png").getImage()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNameP1 = new javax.swing.JLabel();
        ava1View = new javax.swing.JPanel();
        vsView = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNameP2 = new javax.swing.JLabel();
        ava2View = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jPanel1.setOpaque(false);

        lblNameP1.setFont(new java.awt.Font("Ink Free", 3, 24)); // NOI18N
        lblNameP1.setForeground(new java.awt.Color(255, 255, 255));
        lblNameP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameP1.setText("jLabel1");

        ava1View.setOpaque(false);
        ava1View.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ava1View, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameP1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(ava1View, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNameP1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1);

        vsView.setOpaque(false);
        vsView.setLayout(new java.awt.BorderLayout());
        add(vsView);

        jPanel2.setOpaque(false);

        lblNameP2.setFont(new java.awt.Font("Ink Free", 3, 24)); // NOI18N
        lblNameP2.setForeground(new java.awt.Color(255, 255, 255));
        lblNameP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameP2.setText("jLabel2");

        ava2View.setOpaque(false);
        ava2View.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ava2View, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameP2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(ava2View, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNameP2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ava1View;
    private javax.swing.JPanel ava2View;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNameP1;
    private javax.swing.JLabel lblNameP2;
    private javax.swing.JPanel vsView;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        try {
            room = mainscreen.requestStub.visitRoom(room, mainscreen.player.getId());
            mainscreen.displayGameRoomView(room, curPID);
        } catch (RemoteException ex) {
            Logger.getLogger(RoomInfoPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }
}
