package views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import mainscreen.PlayerScreen;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Player;

/**
 *
 * @author thuy
 */
public class SignUpPane extends javax.swing.JPanel implements KeyListener {

    /**
     * Creates new form SignInPane
     */
    PlayerScreen mainScreen;

    public SignUpPane(PlayerScreen fr) {
        initComponents();
        mainScreen = fr;
        txtAcc.addKeyListener(this);
        txtName.addKeyListener(this);
        txtPass.addKeyListener(this);
        btnOke.setEnabled(false);

    }

    public Player getDataPlayer() {
        Player p = new Player();
        p.setName(txtName.getText());
        p.setAcc(txtAcc.getText());
        p.setPass(txtPass.getText());
        if (radAva1.isSelected()) {
            p.setAva("images/ava1.png");
        } else {
            p.setAva("images/ava2.png");
        }
        p.setScore(0);
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        backgroundPane1 = new views.BackgroundPane();
        jPanel1 = new javax.swing.JPanel();
        btnSignIn = new javax.swing.JButton();
        btnOke = new javax.swing.JButton();
        txtAcc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblNameReport = new javax.swing.JLabel();
        lblAccReport = new javax.swing.JLabel();
        lblPassReport = new javax.swing.JLabel();
        radAva1 = new javax.swing.JRadioButton();
        radAva2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        backgroundPane1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SIGN UP", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Ink Free", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        btnSignIn.setBackground(new java.awt.Color(255, 255, 255));
        btnSignIn.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        btnSignIn.setText("SIGN IN");
        btnSignIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnOke.setBackground(new java.awt.Color(255, 255, 255));
        btnOke.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        btnOke.setText("OK");
        btnOke.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkeActionPerformed(evt);
            }
        });

        txtAcc.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ink Free", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account:");

        txtName.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        lblNameReport.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        lblNameReport.setForeground(new java.awt.Color(153, 153, 153));
        lblNameReport.setText("(Check Name...)");

        lblAccReport.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        lblAccReport.setForeground(new java.awt.Color(153, 153, 153));
        lblAccReport.setText("(Check Account...)");

        lblPassReport.setFont(new java.awt.Font("Ink Free", 3, 18)); // NOI18N
        lblPassReport.setForeground(new java.awt.Color(153, 153, 153));
        lblPassReport.setText("(Check Pass)");

        buttonGroup1.add(radAva1);
        radAva1.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        radAva1.setForeground(new java.awt.Color(204, 204, 255));
        radAva1.setText("Xiao Zhan");
        radAva1.setIcon(new javax.swing.ImageIcon("E:\\SPR20\\PRJ\\TicTacToeProject\\XO_Client\\images\\ava1-icon.png")); // NOI18N
        radAva1.setSelectedIcon(new javax.swing.ImageIcon("E:\\SPR20\\PRJ\\TicTacToeProject\\XO_Client\\images\\ava1-selected.png")); // NOI18N
        radAva1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radAva1StateChanged(evt);
            }
        });

        buttonGroup1.add(radAva2);
        radAva2.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        radAva2.setForeground(new java.awt.Color(255, 204, 204));
        radAva2.setText("Wang Ibo");
        radAva2.setIcon(new javax.swing.ImageIcon("E:\\SPR20\\PRJ\\TicTacToeProject\\XO_Client\\images\\ava2-icon.png")); // NOI18N
        radAva2.setSelectedIcon(new javax.swing.ImageIcon("E:\\SPR20\\PRJ\\TicTacToeProject\\XO_Client\\images\\ava2-selected.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Ink Free", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Ink Free", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Avatar:");

        jLabel7.setFont(new java.awt.Font("Ink Free", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name: ");

        txtPass.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(btnSignIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAcc)
                    .addComponent(lblNameReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAccReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPassReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(222, 222, 222))
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(radAva1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(btnOke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(radAva2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(txtPass))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNameReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblAccReport)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPassReport)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radAva2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radAva1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOke, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        backgroundPane1.add(jPanel1, new java.awt.GridBagConstraints());

        add(backgroundPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void radAva1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radAva1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radAva1StateChanged

    private void btnOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkeActionPerformed
        try {
            // TODO add your handling code here:
            mainScreen.requestStub.signUp(this.getDataPlayer());

            //Show mess dialog
            JOptionPane.showMessageDialog(mainScreen, "Regist Successfully!");

            //remove this
            mainScreen.remove(this);

            //display sign in view
            mainScreen.displaySigninView();
        } catch (RemoteException ex) {
            Logger.getLogger(SignUpPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOkeActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        mainScreen.remove(this);
        mainScreen.displaySigninView();
    }//GEN-LAST:event_btnSignInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.BackgroundPane backgroundPane1;
    private javax.swing.JButton btnOke;
    private javax.swing.JButton btnSignIn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccReport;
    private javax.swing.JLabel lblNameReport;
    private javax.swing.JLabel lblPassReport;
    private javax.swing.JRadioButton radAva1;
    private javax.swing.JRadioButton radAva2;
    private javax.swing.JTextField txtAcc;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {

    }

    @Override
    public void keyPressed(KeyEvent e) {

    }

    @Override
    public void keyReleased(KeyEvent e) {
        boolean validData = true;

        //check name empty
        if (txtName.getText().isEmpty()) {
            lblNameReport.setText("Name can not empty!");
            lblNameReport.setForeground(Color.yellow);
            validData = validData & false;
        } else {
            lblNameReport.setText("Valid!");
            lblNameReport.setForeground(Color.green);
            validData = validData & true;
        }

        //check pass empty
        if (txtPass.getText().isEmpty()) {
            lblPassReport.setText("Password can not empty!");
            lblPassReport.setForeground(Color.yellow);
            validData = validData & false;
        } else {
            lblPassReport.setText("Valid!");
            lblPassReport.setForeground(Color.green);
            validData = validData & true;
        }

        //check acc existed/empty
        try {
            if (txtAcc.getText().isEmpty()) {
                lblAccReport.setText("Account can not empty!");
                lblAccReport.setForeground(Color.yellow);
                validData = validData & false;
            } else if (mainScreen.requestStub.isExist(txtAcc.getText())) {
                lblAccReport.setText("Account already exist!");
                lblAccReport.setForeground(Color.red);
                validData = validData & false;
            } else {
                lblAccReport.setText("Valid!");
                lblAccReport.setForeground(Color.green);
                validData = validData & true;
            }
        } catch (RemoteException ex) {
            Logger.getLogger(SignUpPane.class.getName()).log(Level.SEVERE, null, ex);
        }

        //set enable button oke
        if (validData) {
            btnOke.setEnabled(true);
        } else {
            btnOke.setEnabled(false);
        }

    }
}
