package mainscreen;

import ifunctions.IRequest;
import views.SignInPane;
import views.SignUpPane;
import java.awt.CardLayout;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Player;
import model.Room;
import sun.applet.Main;
import views.GameRoomPane;
import views.OverviewPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author thuy
 */
public class PlayerScreen extends javax.swing.JFrame {

    /**
     * Creates new form UserScreen
     */
    public Player player = null;
    public IRequest requestStub;

    public PlayerScreen() {
        initComponents();
        CoverPane.setLayout(new CardLayout());
        setLocationRelativeTo(null);
        setTitle("Tic-Tac-Toe");

        //Connect RMI
        try {
            requestStub = (IRequest) Naming.lookup("rmi://localhost:8787/request");
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Display Signup View
        displaySigninView();
    }

    public void displaySigninView() {
        SignInPane signinPane = new SignInPane(this);
        CoverPane.add("signinPane", signinPane);
        CardLayout layout = (CardLayout) CoverPane.getLayout();
        layout.show(CoverPane, "signinPane");
    }

    public void displaySignupView() {
        SignUpPane signupPane = new SignUpPane(this);
        CoverPane.add("signupPane", signupPane);
        CardLayout layout = (CardLayout) CoverPane.getLayout();
        layout.show(CoverPane, "signupPane");
    }

    public void displayOverView() throws RemoteException {
        OverviewPane overviewPane = new OverviewPane(this);
        CoverPane.add("overviewPane", overviewPane);
        CardLayout layout = (CardLayout) CoverPane.getLayout();
        layout.show(CoverPane, "overviewPane");
    }
    
    public void displayGameRoomView(Room r, int curPID) throws RemoteException {
        GameRoomPane gameroomPane = new GameRoomPane(this, r, curPID);
        CoverPane.add("gameroomPane", gameroomPane);
        CardLayout layout = (CardLayout) CoverPane.getLayout();
        layout.show(CoverPane, "gameroomPane");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CoverPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout CoverPaneLayout = new javax.swing.GroupLayout(CoverPane);
        CoverPane.setLayout(CoverPaneLayout);
        CoverPaneLayout.setHorizontalGroup(
            CoverPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        CoverPaneLayout.setVerticalGroup(
            CoverPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(CoverPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CoverPane;
    // End of variables declaration//GEN-END:variables
}
